fn main() {
    dbg!(nth_digit(999, 11));

    dbg!(count_fives(1, 101));

    dbg!(find_substring_naive(1, "123456789"));
    dbg!(find_substring_naive(1, "11111"));

    dbg!(find_substring_faster(1, "123456789"));
    dbg!(find_substring_faster(1, "11111"));
    dbg!(find_substring_faster(1, "987654321"));
}

/**
A string is generated by joining together, in order, all the integers starting with n. We are interested in
which digit appears in the ith
position in this string.
For example:
• If we start at 6 the string will begin 678910111213141516…;
• The 11th
digit in this string is 1 and the 12th
is 3;
• If we start at 999 the string will begin 999100010011002… and the 10th
digit is 0.

Write a program that reads in integers n then i (both between 1 and 259
inclusive),
indicating the first number that appears in the string and the required digit from the
string respectively. You should output the digit in the ith
position in the string.

Sample run
999 11
1
*/
fn nth_digit(mut n: i32, i: usize) -> u32 {
    let mut s = String::new();
    while s.len() < i {
        s.push_str(&n.to_string());
        n += 1;
    }
    s.chars().nth(i - 1).unwrap().to_digit(10).unwrap()
}

/**
 Consider the string generated when n = 1.

 How many occurrences of the digit 5 appear in the first 101
digits?
 */
fn count_fives(mut n: i32, i: usize) -> usize {
    let mut s = String::new();

    while s.len() < i {
        s.push_str(&n.to_string());
        n += 1;
    }
    s.chars().take(i - 1).filter(|c| *c == '5').count()
}

/**
Naive solution to this problem:

Consider the string generated when n = 1. The substring 123456789 first appears in this string between
positions 1 and 9 inclusive.String.IndexString.Index
Where does the substring 11111 first appear? Where does the substring 987654321 first appear?
*/
fn find_substring_naive(mut n: i32, substring: &str) -> (usize, usize) {
    let mut s = String::new();

    loop {
        s.push_str(&n.to_string());
        n += 1;
        if let Some(index) = s.find(substring) {
            return (index + 1, index + substring.len());
        }
    }
}

/**
Slightly better solution to this problem:

Consider the string generated when n = 1. The substring 123456789 first appears in this string between
positions 1 and 9 inclusive.String.IndexString.Index
Where does the substring 11111 first appear? Where does the substring 987654321 first appear?
*/
fn find_substring_faster(mut n: i32, substring: &str) -> (usize, usize) {
    let mut s = String::new();
    let mut length = 0;

    let substring_prefixes: Vec<String> = (1..substring.len())
        .rev()
        .map(|n| substring.chars().take(n).collect())
        .collect();

    loop {
        s.push_str(&n.to_string());
        if let Some(index) = s.find(substring) {
            return (index + length + 1, index + length + substring.len());
        }

        let mut found = false;
        for prefix in &substring_prefixes {
            if s.ends_with(prefix) {
                found = true;
                length += s.len() - prefix.len();
                s.clear();
                s.push_str(prefix);
                break;
            }
        }
        if !found {
            length += s.len();
            s.clear();
        }
        n += 1;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_nth_digit() {
        let expected = 1;
        let actual = nth_digit(999, 11);
        assert_eq!(expected, actual);
    }

    #[test]
    fn test_count_fives() {
        assert_eq!(11, count_fives(1, 101));
    }

    #[test]
    fn test_find_substring_naive() {
        assert_eq!((1, 9), find_substring_naive(1, "123456789"));
        assert_eq!((223, 227), find_substring_naive(1, "11111"));
    }

    #[test]
    fn test_find_substring_faster() {
        assert_eq!((1, 9), find_substring_faster(1, "123456789"));
        assert_eq!((223, 227), find_substring_faster(1, "11111"));
    }

    #[test]
    fn test_find_substring_faster_big() {
        assert_eq!(
            (1677777779, 1677777787),
            find_substring_faster(1, "987654321")
        );
    }
}
